name: Build libwallet
on:
  release:
   types:
     - created
jobs:
  build_libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build libraries
        run: |
          ${GITHUB_WORKSPACE}/base_layer/wallet_ffi/mobile_build.sh